export interface CryptoList{
    coinId : number,
    coinNameFa: string,
    coinNameEn: string,
    price: number,
    priceToman : number,
    symbol : string, 
    // symbolPic : string
}

export const coins =  [
{
    coinId: 1,
    coinNameFa: "بیت کوین",
    coinNameEn: "Bitcoin",
    price: 43482,
    priceToman: 11652063565,
    symbol : "BTC", 
},
{
    coinId: 2,
    coinNameFa: "اتریوم",
    coinNameEn: "Ethereum",
    price: 3095.62,
    priceToman: 82944255,
    symbol : "ETH", 
},
{
    coinId: 3,
    coinNameFa: "تتر" ,
    coinNameEn: "Tether",
    price: 1.00,
    priceToman: 26818,
    symbol : "USDT", 
},
{
    coinId: 4 ,
    coinNameFa: "بایننس کوین" ,
    coinNameEn: "BNB" ,
    price: 416.62,
    priceToman: 11082315,
    symbol : "BNB", 
},
{
    coinId: 5,
    coinNameFa: "یو اس دی کوین",
    coinNameEn: "USD Coin",
    price: 0.999334,
    priceToman: 26537,
    symbol : "USDC", 
},
{
    coinId: 6,
    coinNameFa: "کاردانو",
    coinNameEn: "Cardano",
    price: 1.15,
    priceToman: 30716,
    symbol : "ADA", 
},
{
    coinId: 7,
    coinNameFa: "ریپل",
    coinNameEn: "XRP",
    price: 0.844060,
    priceToman: 22460,
    symbol : "XRP", 
},
{
    coinId: 8,
    coinNameFa: "سولانا",
    coinNameEn: "Solana",
    price: 106.22,
    priceToman: 2846867,
    symbol : "SOL", 
},
{
    coinId: 9,
    coinNameFa: "لونا",
    coinNameEn: "Terra",
    price: 56.14,
    priceToman: 1492127,
    symbol : "LUNA", 
},
{
    coinId: 10,
    coinNameFa: "دوج کوین",
    coinNameEn: "Dogecoin",
    price: 0.153297,
    priceToman: 4108,
    symbol : "DOGE", 
},
{
    coinId: 11,
    coinNameFa: "پولکادات",
    coinNameEn: "Polkadot",
    price: 20.50,
    priceToman: 549336,
    symbol : "DOT", 
},
{
    coinId: 12,
    coinNameFa: "اولنچ",
    coinNameEn: "Avalanche",
    price: 90.85,
    priceToman: 2438420,
    symbol : "AVAX", 
},
{
    coinId: 13,
    coinNameFa: "پالیگان",
    coinNameEn: "Polygon",
    price: 1.86,
    priceToman: 50014,
    symbol : "MATIC", 
},
{
    coinId: 14,
    coinNameFa: "کازماس",
    coinNameEn: "Cosmos",
    price: 29.32,
    priceToman: 781985,
    symbol : "ATOM", 
},
{
    coinId: 15,
    coinNameFa: "لایت کوین",
    coinNameEn: "Litecoin",
    price: 133.48,
    priceToman: 3581274,
    symbol : "LTC", 
},
]